# Generated by Django 2.2.1 on 2019-05-11 17:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('video_file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 5, 11, 21, 5, 26, 222185))),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2019, 5, 11, 21, 5, 26, 222185))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
