# Generated by Django 2.2.1 on 2019-05-16 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20190511_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 36, 12, 159678)),
        ),
        migrations.AlterField(
            model_name='video',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 36, 12, 159702)),
        ),
    ]
